import "./globals.css"
import { ReactNode } from "react"
import type { Metadata } from "next"
import Flex from "@/components/Flex"

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
}


export interface Props {
	children: ReactNode
}

export default function Layout({ children }: Props) {
	return (
		<html>
			<body>
				<header>
					<Flex>
						<Flex vertical>
							<span>tmcnab.dev</span>
							<span>engineer, husband, socialist</span>
						</Flex>
						<Flex>
							<select>
								<option>index</option>
								<option>about</option>
							</select>
							<select>
								<option>blog</option>
								<option>2024-09-21 • Something Devestating</option>
							</select>

							<span>github</span>
						</Flex>
					</Flex>
				</header>
				{children}
			</body>
		</html >
	)
}
