import './layout.css'
import "./globals.css"
import { ReactNode } from "react"
import ArticleSelect from '@/components/ArticleSelect'
import Flex from "@/components/Flex"
import Link from 'next/link'
import PageSelect from '@/components/PageSelect'
import type { Metadata } from "next"
import Button from '@/components/Button'

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
}


export interface Props {
	children: ReactNode
}

export default function Layout({ children }: Props) {
	return (
		<html>
			<body>
				<header>
					<Flex>
						<div>
							<Link className='header-title' href='/'>tmcnab.dev</Link>
							<div className='header-subtitle'>engineer / husband / socialist</div>
						</div>
						<Flex justifyContent='start' vertical>
							<Flex>
								<PageSelect />
								<ArticleSelect />
								<Button>GH</Button>
							</Flex>
						</Flex>
					</Flex>
				</header>
				<main>
					{children}
				</main>
			</body>
		</html >
	)
}
