import './layout.css'
import "./globals.css"
import { ReactNode } from "react"
import Flex from "@/components/Flex"
import type { Metadata } from "next"
import PageSelect from '@/components/PageSelect'
import ArticleSelect from '@/components/ArticleSelect'
import Link from 'next/link'

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
}


export interface Props {
	children: ReactNode
}

export default function Layout({ children }: Props) {
	return (
		<html>
			<body>
				<header>
					<Flex>
						<Flex vertical>
							<Link className='header-title' href='/'>tmcnab.dev</Link>
							<span className='header-subtitle'>engineer, husband, socialist</span>
						</Flex>
						<Flex>
							<PageSelect />
							<ArticleSelect />
							<button>GH</button>
						</Flex>
					</Flex>
				</header>
				<main>
					{children}
				</main>
			</body>
		</html >
	)
}
